// OpenTPMS — MS5837 Conversion Math Tests
// Host-compiled: cc test_ms5837.c ../src/ms5837.c && ./a.out  (or `make` here)
// Reference values generated by an independent Python implementation of the
// TE MS5837-30BA datasheet math (see docs/implementation-plan.md Task 2).

#include <stdio.h>
#include <stdlib.h>
#include "ms5837.h"

static int g_failures = 0;

#define CHECK_EQ(label, got, want)                                             \
    do {                                                                       \
        long long _g = (long long)(got), _w = (long long)(want);               \
        if (_g != _w) {                                                        \
            printf("FAIL %-34s got %lld, want %lld\n", label, _g, _w);         \
            g_failures++;                                                      \
        } else {                                                               \
            printf("ok   %-34s %lld\n", label, _g);                            \
        }                                                                      \
    } while (0)

#define CHECK(label, cond)                                                     \
    do {                                                                       \
        if (!(cond)) { printf("FAIL %s\n", label); g_failures++; }              \
        else         { printf("ok   %s\n", label); }                            \
    } while (0)

// Coefficients used to generate the reference vectors (plausible mid-range values).
static const ms5837_cal_t CAL = {
    .c1_sens = 34982, .c2_off = 36352, .c3_tcs = 20328,
    .c4_tco  = 22354, .c5_tref = 26646, .c6_tempsens = 26146,
};

typedef struct { uint32_t d1, d2; int32_t p, t; } vector_t;

// Python-generated: pressure in 0.01 mbar (Pa), temperature in 0.01 degC.
static const vector_t VECTORS[] = {
    { /* dT=0 boundary, 20.00C      */ 4460000u, 6821376u,   67670L,  2000L },
    { /* high-temp branch, 28.67C   */ 5600000u, 7100000u,  841090L,  2867L },
    { /* low-temp branch, 2.80C     */ 5300000u, 6300000u,  611320L,   280L },
    { /* very-low branch, -19.35C   */ 5200000u, 5700000u,  530220L, -1935L },
    { /* hot, 37.99C                */ 6900000u, 7400000u, 1757140L,  3799L },
};

static void test_vectors(void)
{
    for (unsigned i = 0; i < sizeof(VECTORS) / sizeof(VECTORS[0]); i++)
    {
        int32_t p, t;
        char label[48];
        ms5837_compensate(&CAL, VECTORS[i].d1, VECTORS[i].d2, &p, &t);
        snprintf(label, sizeof label, "vector %u pressure", i);
        CHECK_EQ(label, p, VECTORS[i].p);
        snprintf(label, sizeof label, "vector %u temperature", i);
        CHECK_EQ(label, t, VECTORS[i].t);
    }
}

static void test_monotonic_pressure(void)
{
    // At fixed temperature, more D1 counts must mean more pressure.
    int32_t prev_p, p, t;
    ms5837_compensate(&CAL, 4000000u, 6821376u, &prev_p, &t);
    for (uint32_t d1 = 4100000u; d1 <= 6900000u; d1 += 100000u)
    {
        ms5837_compensate(&CAL, d1, 6821376u, &p, &t);
        if (p <= prev_p)
        {
            printf("FAIL monotonicity at d1=%u (%ld <= %ld)\n",
                   d1, (long)p, (long)prev_p);
            g_failures++;
            return;
        }
        prev_p = p;
    }
    printf("ok   pressure monotonic in D1\n");
}

static void test_branch_boundaries(void)
{
    // The -15C boundary: temps in (-16, -15] must not blow up or jump wildly.
    // Sweep D2 downward and require temperature output to be monotonic in D2.
    int32_t p, t, prev_t;
    ms5837_compensate(&CAL, 5200000u, 6900000u, &p, &prev_t);
    for (uint32_t d2 = 6890000u; d2 >= 5500000u; d2 -= 10000u)
    {
        ms5837_compensate(&CAL, 5200000u, d2, &p, &t);
        if (t > prev_t)
        {
            printf("FAIL temperature not monotonic in D2 at d2=%u\n", d2);
            g_failures++;
            return;
        }
        prev_t = t;
    }
    printf("ok   temperature monotonic in D2 across all branches\n");
}

static void test_crc(void)
{
    // Build a PROM image with the CAL coefficients and the correct CRC nibble,
    // by brute-forcing the nibble (16 candidates) against the checker itself,
    // then verify corruption is detected. The CRC algorithm is from the
    // datasheet; this test locks its behavior against accidental edits.
    uint16_t prom[MS5837_PROM_WORDS] = {
        0x0123,  // word 0: factory bits (low 12), CRC nibble to be set
        CAL.c1_sens, CAL.c2_off, CAL.c3_tcs, CAL.c4_tco, CAL.c5_tref, CAL.c6_tempsens,
    };
    int valid = -1;
    for (int nib = 0; nib < 16; nib++)
    {
        prom[0] = (uint16_t)((nib << 12) | 0x0123);
        if (ms5837_prom_crc_ok(prom)) { valid = nib; break; }
    }
    CHECK("crc: exactly one nibble validates", valid >= 0);
    prom[0] = (uint16_t)((valid << 12) | 0x0123);
    CHECK("crc: accepts valid prom", ms5837_prom_crc_ok(prom));

    prom[3] ^= 0x0001;   // flip one bit of C3
    CHECK("crc: rejects corrupted prom", !ms5837_prom_crc_ok(prom));
    prom[3] ^= 0x0001;

    // cal unpack sanity
    ms5837_cal_t cal;
    ms5837_cal_from_prom(prom, &cal);
    CHECK("cal unpack c1", cal.c1_sens == CAL.c1_sens);
    CHECK("cal unpack c6", cal.c6_tempsens == CAL.c6_tempsens);
}

int main(void)
{
    test_vectors();
    test_monotonic_pressure();
    test_branch_boundaries();
    test_crc();

    if (g_failures) { printf("\n%d FAILURE(S)\n", g_failures); return 1; }
    printf("\nALL TESTS PASSED\n");
    return 0;
}
